### ISSUE TITLE
프로젝트 관련 질문

### ISSUE THREAD

**Issue by Kick-snare** [y0jpnu/Introduction-to-Internet-and-Web_059_2101#2]
안녕하세요 조교님. 인웹기 강의를 수강중인 학생 홍유준이라고 합니다.
프로젝트 관련하여 질문이 있어 몇가지 있어 메일드렸는데 답장이 없어 issues 에 질문남깁니다.

1. ppt에서 node js 로컬 웹 서버에서 json을 파싱하지않고 라우팅하기만 하라고 하셨는데, 
그럼 모두 js안에서 ajax로 api 를 받아와 처리하는건가요?

2. 웹 템플릿엔진 (jade,pug등) 이나 css 전처리기 또는 기타 라이브러리를 프로젝트에 활용해도 되나요?

3. 프로젝트로 만든 웹사이트는 반응형으로 만들어야 하나요? 모바일 대응까지 고려해야하는지 궁금합니다.

이상입니다. 감사합니다.

**Comment by y0jpnu** [comment]
안녕하세요 웹기초 조교 김영주입니다.

답변이 늦었습니다.

1. 네.
이번 웹기초 강의는 basic 강의로 front-end와 back-end 중 front-end에 집중하고 있습니다. back-end의
경우 심화 강의에서 학습하기를 권장하고 있습니다. 그런 의미에서 프로젝트에서 " web server의 기능은 routing과 API
server로부터 받은 data를 forwarding하는 역할만 구현할 것"을 요구하고 있습니다. open api로 얻은 값을 별도로
db에 저장/추출하여 그값을 parsing을 하지 말라는 이야기 입니다.

2. 아니요.
수업시간에 배운 범위 안에서(12주차포함) 최대한 활용해주세요.


3. 모바일 대응까지 고려하지 않습니다!

좋은 하루 되세요.
감사합니다.
김영주.

>

**Comment by Kick-snare** [comment]
네 답변 감사합니다
